table Table1
	lineageTag: b0589cca-337f-4419-8b59-88df126a6320

	column ID
		dataType: int64
		formatString: 0
		lineageTag: cae91b38-75cf-4c75-b6e0-0961137091c6
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'What is your current skill level in Power BI?'
		dataType: string
		lineageTag: 5a359624-2535-4a2a-960c-ae425afa8784
		summarizeBy: none
		sourceColumn: What is your current skill level in Power BI?

		annotation SummarizationSetBy = Automatic

	partition Table1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\Downloads\Registration for Power BI & Git Live Session Sunday, April 13, 2025(1-67).xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"ID", Int64.Type}, {"Start time", type datetime}, {"Completion time", type datetime}, {"Email", type text}, {"Name", type any}, {"Last modified time", type any}, {"Full Name", type text}, {"E-mail", type text}, {"What is your current skill level in Power BI?", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Last modified time", "Start time", "Completion time", "Email", "Name", "Full Name", "E-mail"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

